const routers = [
    {
        path:'/list',
        meta:{
            title:'为你写诗',
            detail:"进入界面"
        },
        component:(resolve)=>require(['../views/list.vue'],resolve)
    },
    {
        path:'/read',
        meta:{
            title:'赏诗',
            detail:"阅诗分类"
        },
        component:(resolve)=>require(['../views/read.vue'],resolve)
    },
    {
        path:'/menu',
        meta:{
            title:"为你写诗",
            detail:"菜单==>赏诗，写诗"
        },
        component:(resolve)=>require(['../views/menu.vue'],resolve)
    },
    {
        path:'/poemList/:id',
        meta:{
            title:"赏诗",
            detail:"具体类别诗歌展开"
        },
        component:(resolve)=>require(['../views/poemList.vue'],resolve)
    },
    {
        path:'/write',
        meta:{
            title:"写诗",
            detail:"写诗界面"
        },
        component:(resolve)=>require(['../views/write.vue'],resolve)
    },
    {
        path:"/result",
        meta:{
            title:"作诗结果",
            detail:"写诗结果"
        },
        component:(resolve)=>require(['../views/result.vue'],resolve)
    },
    {
        path:'*',
        redirect:'/list'
    }
];
export default routers
